pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/abhishek853/clinicease.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t clinicease-site .'
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    // Stop old container if exists
                    sh 'docker rm -f clinicease || true'
                    // Run new container on port 80
                    sh 'docker run -d --name clinicease -p 80:80 clinicease-site'
                }
            }
        }
    }
}
